spring.application.name=notification-service
server.port=8084


# H2 (console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:notifdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ (local Docker default)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Logging minimal
logging.level.org.springframework.amqp=INFO
# m�me secret si service doit valider tokens
app.jwt.secret=K3yVeryS3cret_ChangeThisToASecureRandomString_AtLeast_32_bytes_long!
